---
- name: Tower credential demo playbook
  hosts: all
  vars:
    my_controller: "192.168.0.106"
    my_username: "admin"
    my_password: "redhat"
    validate_certs: false
  tasks:
  - name: Create a valid Machine credential with Signed SSH Certificate
    ansible.tower.tower_credential:
      name: Machine Signed SSH Certificate example
      organization: Default
      state: present
      credential_type: Machine
      inputs:
        ssh_public_key_data: "{{ lookup('file', '/tmp/id_rsa') }}"
      tower_host: "{{ my_controller }}"
      tower_username: "{{ my_username }}"
      tower_password: "{{ my_password }}"
      validate_certs: "{{ validate_certs }}"
