---
- hosts: all
  tasks:
  - name: Create a valid Machine credential with Signed SSH Certificate
    ansible.tower.tower_credential:
      name: Machine Signed SSH Certificate example
      organization: Default
      state: present
      credential_type: Machine
      inputs:
        ssh_public_key_data: "{{ lookup('file', '/tmp/id_rsa') }}"
